# Generated by Django 4.1.7 on 2023-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khalidapp', '0004_tvshows_likeflag_alter_tvshows_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='likeCount',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='likeFlag',
        ),
        migrations.AddField(
            model_name='user',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='likeFlag',
            field=models.BooleanField(default=False),
        ),
    ]
