# Generated by Django 4.1.7 on 2023-03-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khalidapp', '0005_remove_tvshows_likecount_remove_tvshows_likeflag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeCount', models.IntegerField(default=0)),
                ('likeFlag', models.BooleanField(default=False)),
                ('tvshow', models.ManyToManyField(related_name='shows', to='Khalidapp.tvshows')),
                ('user', models.ManyToManyField(related_name='users', to='Khalidapp.user')),
            ],
        ),
    ]
