# Generated by Django 4.1.7 on 2023-03-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khalidapp', '0006_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='user',
            field=models.ManyToManyField(related_name='users', to='Khalidapp.user'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ManyToManyField(related_name='usersLikes', to='Khalidapp.user'),
        ),
    ]
